### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by mathiascode** [cuberite/HungerGames#7]
This plugin has no license at the moment.

**Comment by the-maldridge** [comment]
I'd like to suggest the MIT license.  Its short and to the point.  Should be less than 10 minutes to commit it.

I'd like to make a few patches but unfortunately I cannot do so until a license is in place :/

**Comment by madmaxoft** [comment]
I went through the commits and there are only four people who have actually contributed to the current code - @NiLSPACE , @sphinxc0re , @mathiascode and myself. So we need the four of us to agree on a license.

I don't care really, I consider all my code public domain, and I'll accept any open-source license, too - the less restrictive, the better.

**Comment by the-maldridge** [comment]
Sounds good. Please not public domain though. That is a legally dubious one
and is difficult to contribute to for employees in some US states.

**Comment by sphinxc0re** [comment]
How about Apache 2 / MIT ?

**Comment by madmaxoft** [comment]
I agree.

**Comment by NiLSPACE** [comment]
Sure

**Comment by bearbin** [comment]
@mathiascode Do you accept the suggested license?

**Comment by mathiascode** [comment]
Yes

**Comment by sphinxc0re** [comment]
So will it be both now? Apache 2 **and** MIT ?

**Comment by madmaxoft** [comment]
That would be a needless overkill. Since Cuberite itself is Apache2, let's make this Apache2, too.

**Comment by bearbin** [comment]
Fixed by #8
